# Generated by Django 5.0.6 on 2024-08-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_panel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='app.user'),
        ),
    ]
