# Generated by Django 5.0.6 on 2024-08-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_panel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compname', models.CharField(max_length=30)),
                ('posx', models.PositiveBigIntegerField()),
                ('posy', models.PositiveBigIntegerField()),
                ('panelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app.panel')),
            ],
        ),
    ]
