# Generated by Django 5.0.6 on 2024-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='posx',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='component',
            name='posy',
            field=models.IntegerField(),
        ),
    ]
