# Generated by Django 5.0.6 on 2024-08-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_component_posx_alter_component_posy'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
