# Generated by Django 5.0.6 on 2024-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_component_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='panelname',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='panel',
            constraint=models.UniqueConstraint(fields=('panelname', 'userid'), name='unique_panel_per_user'),
        ),
    ]
